#!/usr/bin/env python3
"""Generate the small, redistributable OBJ cases shipped with teleop_maniskill.

The meshes deliberately use only Python's standard library.  Running this file
from any working directory deterministically rewrites the two procedural
``<case>/mesh/simplified.obj`` files next to it.

The bundled cup is an upstream DGN mug asset and is intentionally not generated
or overwritten here.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import math
from pathlib import Path
from typing import Iterable


Vec3 = tuple[float, float, float]
Face = tuple[int, int, int]


@dataclass
class Mesh:
    vertices: list[Vec3] = field(default_factory=list)
    faces: list[Face] = field(default_factory=list)

    def vertex(self, xyz: Vec3) -> int:
        """Append a vertex and return its zero-based index."""
        self.vertices.append(xyz)
        return len(self.vertices) - 1

    def triangle(self, a: int, b: int, c: int) -> None:
        self.faces.append((a, b, c))

    def quad(self, a: int, b: int, c: int, d: int) -> None:
        self.triangle(a, b, c)
        self.triangle(a, c, d)


def _ring(mesh: Mesh, radius: float, z: float, segments: int) -> list[int]:
    return [
        mesh.vertex(
            (
                radius * math.cos(2.0 * math.pi * i / segments),
                radius * math.sin(2.0 * math.pi * i / segments),
                z,
            )
        )
        for i in range(segments)
    ]


def _connect_rings(mesh: Mesh, lower: list[int], upper: list[int]) -> None:
    """Join CCW rings with outward-facing side triangles."""
    assert len(lower) == len(upper)
    for i, a in enumerate(lower):
        j = (i + 1) % len(lower)
        mesh.quad(a, lower[j], upper[j], upper[i])


def _cap(mesh: Mesh, ring: list[int], z: float, *, upward: bool) -> None:
    center = mesh.vertex((0.0, 0.0, z))
    for i, current in enumerate(ring):
        following = ring[(i + 1) % len(ring)]
        if upward:
            mesh.triangle(center, current, following)
        else:
            mesh.triangle(center, following, current)


def make_can(segments: int = 48) -> Mesh:
    """A sealed beverage can with subtly bevelled top and bottom rims."""
    mesh = Mesh()
    rings = [
        _ring(mesh, 0.34, -0.50, segments),
        _ring(mesh, 0.38, -0.46, segments),
        _ring(mesh, 0.38, +0.46, segments),
        _ring(mesh, 0.34, +0.50, segments),
    ]
    for lower, upper in zip(rings, rings[1:]):
        _connect_rings(mesh, lower, upper)
    _cap(mesh, rings[0], -0.50, upward=False)
    _cap(mesh, rings[-1], +0.50, upward=True)
    return mesh


def make_box() -> Mesh:
    """A closed rectangular carton, 0.85 x 0.65 x 1.00 units."""
    mesh = Mesh()
    x, y, z = 0.425, 0.325, 0.50
    vertices: Iterable[Vec3] = (
        (-x, -y, -z),
        (+x, -y, -z),
        (+x, +y, -z),
        (-x, +y, -z),
        (-x, -y, +z),
        (+x, -y, +z),
        (+x, +y, +z),
        (-x, +y, +z),
    )
    indices = [mesh.vertex(v) for v in vertices]
    a, b, c, d, e, f, g, h = indices
    mesh.quad(a, d, c, b)  # bottom
    mesh.quad(e, f, g, h)  # top
    mesh.quad(a, b, f, e)  # -Y
    mesh.quad(b, c, g, f)  # +X
    mesh.quad(c, d, h, g)  # +Y
    mesh.quad(d, a, e, h)  # -X
    return mesh


def write_obj(path: Path, mesh: Mesh, object_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Procedurally generated by generate_builtin_objects.py",
        "# Units are normalized object units; teleop default scale is 0.08 m/unit.",
        f"o {object_name}",
    ]
    lines.extend(f"v {x:.9f} {y:.9f} {z:.9f}" for x, y, z in mesh.vertices)
    lines.append("s off")
    lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in mesh.faces)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    root = Path(__file__).resolve().parent
    cases = {
        "can": make_can(),
        "box": make_box(),
    }
    for name, mesh in cases.items():
        output = root / name / "mesh" / "simplified.obj"
        write_obj(output, mesh, name)
        print(f"{name}: {len(mesh.vertices)} vertices, {len(mesh.faces)} faces -> {output}")


if __name__ == "__main__":
    main()
