[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "multiview_hand_capture"
version = "0.1.0"
description = "Stereo Camera Hand Tracking package"
dependencies = [
    "opencv-python",
    "numpy",
    "matplotlib",
    "mediapipe"
]

[tool.setuptools]
packages = ["MultiViewHandCapture"]